- id: do-not-commit
  name: do-not-commit
  description: Check for DO NOT COMMIT
  entry: pre-commit/do-not-commit
  language: script
  stages: [commit]
- id: python-unittest
  name: python-unittest
  description: Run python unittest
  entry: pre-push/python-unittest
  language: script
