#!/bin/bash
remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
  if [ "$remote_sha" = $z40 ]
  then
    # New branch, examine all commits
    range="$local_sha"
  else
    # Update to existing branch, examine new commits
    range="$remote_sha..$local_sha"
  fi

  # Check for WIP commit
  commit=`git rev-list -n 1 --grep 'DO NOT PUSH' -i "$range"`
  if [ -n "$commit" ]
  then
    echo >&2 "$local_ref says DO NOT PUSH"
    exit 1
  fi
done

exit 0
